### ISSUE TITLE
Encoding/Decoding i8/i16/i32/i64 types

### ISSUE THREAD

**Issue by tailhook** [twittner/cbor-codec#7]
I've assumed that `i32` and similar methods decode *unsigned* value. But in current implementation they decode *negative* value only. I know that negative values have different opcode in CBOR protocol, but I still think API is wrong.

When I'm reading a value I don't know is it negative or not, just like I don't know if it 8 or 16 or 32 bits. So I believe it's just a bug, and that both encoding and decoding of i32 should work with positive values. Right?

**Comment by twittner** [comment]
Major type 1 ("negative integer") is somewhat challenging as the value range may very well exceed the ones of `i8` et al. I agree tough, that all values within `i8::MIN` and `i8::MAX` should be supported (likewise for `i16`, `i32`, and `i64`). A further complication involves generic encoding/decoding using the `Value` AST. A map which starts out with a key `Key::I16(200)` may be parsed differently, thus ending up maybe with a `Key::U8(200)` (although unsigned key types have the same problem already).

To cut it short, the [`num`](https://github.com/twittner/cbor-codec/compare/num) branch supports mixed integers and removes the generic decoder and its supporting infrastructure (`Value` etc). `GenericDecoder` was originially motivated by the need to decode heterogenous maps and arrays which is now possible directly and to skip over unknown values which is also possible now using the direct decoder. Would this be okay for you?

**Comment by tailhook** [comment]
Yes, I don't use `GenericDecoder`.

**Comment by twittner** [comment]
I have changed my mind w.r.t. dropping `GenericDecoder`. The `int` branch contains the latest version which fixes what this issue is about. Could you check that it works for you? One outstanding question is whether there is a better way to handle a possible integer overflow when decoding `i64`. I thought about using [`num::bigint::BigInt`](http://doc.rust-lang.org/num/num/bigint/struct.BigInt.html) for this purpose (maybe behind a feature). Any objections to depending on the `num` library?

**Comment by tailhook** [comment]
Yeah, all my stuff works on `int` branch as well. I will publish rebased #8 soon (but general feedback before is also appreciated).

About `BigInt` issue: my project which uses this library uses `num` too, so I don't mind linking to it. But usually I'm trying to avoid bloat in the libraries, so putting it behind a feature is probably better. Especially given that it's mostly for completeness, as I don't think that there are a lot of people who deal with overflowing i64 in practice.

Also it's actual only for GenericDecoder right? As overflowing integer types are just expected situation when using Decoder anyway.

**Comment by twittner** [comment]
> Also it's actual only for GenericDecoder right? As overflowing integer types are just expected situation when using Decoder anyway.

I would probably still add `fn int(&mut self) -> DecodeResult<BigInt>` to `Decoder` as well, in case one wants to handle `i64` without overflow errors.

**Comment by twittner** [comment]
> I thought about using `num::bigint::BigInt` for this purpose

It occured to me that since `u64` covers the whole value range, we do not need to use `BigInt` to support non-overflowing negative integers. Instead we can pair the `u64` with a boolean marker to indicate negativity. I have created [another branch](https://github.com/twittner/cbor-codec/compare/integer) which implements this approach. What do you think about it?

**Comment by tailhook** [comment]
For my taste I'd better use enum `Positive(u64)/Negative(u64)`. But in fact I don't have a use case for this stuff so I'm not sure. For roundtrip decoding-encoding both should be reasonably ok.

**Comment by twittner** [comment]
That's a jolly good idea! I've updated the branch accordingly. Better now?

**Comment by tailhook** [comment]
Yes. Looks good.

**Comment by twittner** [comment]
Thanks.
